### PR TITLE
Allow overriding rsyslog_packages

### PR DESCRIPTION
**Pull request by ct-sce**
---
name: Allow overriding rsyslog_packages
about: Allow overriding rsyslog_packages

---

**Describe the change**
Allow overriding rsyslog_packages
Exemple install rsyslog-gnutls or any other output or protocol support plugin

### CODE REVIEW

**Comment by robertdebock** [comment]
Thanks for the input!

If the packages differ per distribution, I think it would be nice to make a map in `vars/main.yml` and select packages based on the `ansible_os_family` (or `ansible_distribution`) and the "feature" like "gnutls". Something like this:


defaults/main.yml

```yaml
# Set rsyslog_feature to "default" or "gnutls".
rsyslog_feature: default
```

vars/main.yml
```yaml
_rsyslog_packages:
  RedHat:
    default:
      - x
    gnutls:
      - x
      - y
   Debian
    default:
      - z
    gnutls:
      - z
      - x

rsyslog_packages: "{{ _rsyslog_packages[ansible_os_family][rsyslog_feature] }}"
```

I think you are more familiar with rsyslog, so please let me know if my remarks make any sense.

**Comment by ct-sce** [comment]
rsyslog packages seems to be identical between distributions
so maybe we can do

```yml
rsyslog_features:
  - gnutls
  - elastisearch
```

and add a task
```yml
- apt:
    name: "rsyslog-{{ item }}"
  loop: "{{ rsyslog_features }}"
```

**Comment by robertdebock** [comment]
That's good proposal:
- it's intuitive;
- it's expandable.

Please modify the PR a bit to your proposed solution.

Regards, Robert de Bock.

**Comment by ct-sce** [comment]
@robertdebock the PR is now updated with the proposal

Regards, Seb

**Pull request merged**
